version: '3.8'

services:
  api:
    container_name: kids_fashion_api
    ports:
      - '3005:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    build:
      target: development
      context: ./
      dockerfile: Dockerfile
    command: npm run start:dev
    depends_on:
      - database
    networks:
      - kids_fashion
  database:
    container_name: kids_fashion_db
    image: postgres:14-alpine
    tty: true
    ports:
      - '5446:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./postgresql:/usr/share/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: kids_fashion_db
    networks:
      - kids_fashion
volumes:
  minio_data:

networks:
  kids_fashion:
    driver: bridge
